server:
  port: 8080
spring:
  application:
    name: crypto-challenge
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://db:5432/crypto-challenge
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver




