server:
  port: 8081
spring:
  application:
    name: crypto-challenge
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto-challenge
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
        exposure:
          include: ["prometheus"]
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            request: true
  observations:
    key-values:
      application: crypto-challenge